### PR TITLE
Update to WebComponents.js 0.6.0

### PR DESCRIPTION
**Pull request by addyosmani**
I've run the tests locally using our latest build and the output is as expected. You may want to verify the numbers referenced in any tables in blog posts hasn't changed, but we should probably be working against the latest polyfills anyway.

### CODE REVIEW

**Comment by addyosmani** [comment]
r: @tjsavage

**Comment by addyosmani** [comment]
@garlicnation updates to latest in case this fixes the IE/FF snapshot Issues.

**Comment by addyosmani** [comment]
With the last set of commits, I now have the benchmarks working in Firefox:

screen shot 2015-04-02 at 13 21 57

and in IE:

screen shot 2015-04-02 at 13 26 33

Unsure if verified before, but also working in Safari:

screen shot 2015-04-02 at 13 31 15

Compared to what we had failing before, this appears to be an improvement. I hope :)

screen shot 2015-04-02 at 13 36 18

**Comment by garlicnation** [comment]
LGTM

**Comment by ebidel** [comment]
LGTM

**Pull request merged**
